// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Client = require("./Client.bs.js");
var Companies = require("./Companies.bs.js");
var Client$1 = require("@apollo/client");

function App$app(Props) {
  return React.createElement(Client$1.ApolloProvider, {
              client: Client.instance,
              children: React.createElement(React.Fragment, {
                    children: React.createElement(Companies.make, {})
                  })
            });
}

var app = App$app;

var $$default = App$app;

exports.app = app;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
