// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ApolloClient = require("reason-apollo-client/src/ApolloClient.bs.js");
var ApolloClient__Link_Ws = require("reason-apollo-client/src/@apollo/client/link/ws/ApolloClient__Link_Ws.bs.js");
var ApolloClient__Utilities = require("reason-apollo-client/src/@apollo/client/utilities/ApolloClient__Utilities.bs.js");
var ApolloClient__ApolloClient = require("reason-apollo-client/src/@apollo/client/ApolloClient__ApolloClient.bs.js");
var ReasonMLCommunity__ApolloClient = require("reason-apollo-client/src/ReasonMLCommunity__ApolloClient.bs.js");
var ApolloClient__Link_Http_HttpLink = require("reason-apollo-client/src/@apollo/client/link/http/ApolloClient__Link_Http_HttpLink.bs.js");
var ApolloClient__SubscriptionsTransportWs = require("reason-apollo-client/src/subscriptions-transport-ws/ApolloClient__SubscriptionsTransportWs.bs.js");
var ApolloClient__Cache_InMemory_InMemoryCache = require("reason-apollo-client/src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_InMemoryCache.bs.js");

var graphqlEndpoint = "localhost:4000/graphql";

var httpLink = ApolloClient__Link_Http_HttpLink.make((function (param) {
        return "http://localhost:4000/graphql";
      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined);

var wsLink = ApolloClient__Link_Ws.WebSocketLink.make("ws://localhost:4000/graphql", ApolloClient__SubscriptionsTransportWs.ClientOptions.make(undefined, undefined, true, undefined, undefined, undefined, undefined, undefined), undefined, undefined);

var terminatingLink = ReasonMLCommunity__ApolloClient.Link.split((function (param) {
        var definition = ApolloClient__Utilities.getOperationDefinition(param.query);
        if (definition !== undefined && definition.kind === "OperationDefinition") {
          return definition.operation === "subscription";
        } else {
          return false;
        }
      }), wsLink, httpLink);

var instance = ApolloClient.make(undefined, undefined, undefined, Caml_option.some(terminatingLink), ApolloClient__Cache_InMemory_InMemoryCache.make(undefined, undefined, undefined, undefined, undefined, undefined), undefined, undefined, true, undefined, ApolloClient__ApolloClient.DefaultOptions.make(ApolloClient__ApolloClient.DefaultMutateOptions.make(undefined, undefined, true, /* All */2, undefined, undefined), ApolloClient__ApolloClient.DefaultQueryOptions.make(/* NetworkOnly */2, /* All */2, undefined, undefined), ApolloClient__ApolloClient.DefaultWatchQueryOptions.make(/* NetworkOnly */3, /* All */2, undefined, undefined), undefined), undefined, undefined, undefined, undefined, undefined, undefined, undefined);

var $$default = instance;

exports.graphqlEndpoint = graphqlEndpoint;
exports.httpLink = httpLink;
exports.wsLink = wsLink;
exports.terminatingLink = terminatingLink;
exports.instance = instance;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* httpLink Not a pure module */
