// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ApolloClient__React_Hooks_UseQuery = require("reason-apollo-client/src/@apollo/client/react/hooks/ApolloClient__React_Hooks_UseQuery.bs.js");

var Raw = {};

var query = (require("@apollo/client").gql`
  query CompaniesQuery  {
    companies  {
      __typename
      id
      name
    }
  }
`);

function parse(value) {
  var value$1 = value.companies;
  return {
          companies: !(value$1 == null) ? value$1.map(function (value) {
                  if (!(value == null)) {
                    return {
                            __typename: value.__typename,
                            id: value.id,
                            name: value.name
                          };
                  }
                  
                }) : undefined
        };
}

function serialize(value) {
  var value$1 = value.companies;
  var companies = value$1 !== undefined ? value$1.map(function (value) {
          if (value === undefined) {
            return null;
          }
          var value$1 = value.name;
          var value$2 = value.id;
          var value$3 = value.__typename;
          return {
                  __typename: value$3,
                  id: value$2,
                  name: value$1
                };
        }) : null;
  return {
          companies: companies
        };
}

function serializeVariables(param) {
  
}

function makeVariables(param) {
  
}

function makeDefaultVariables(param) {
  
}

var CompaniesQuery_inner = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables
};

var include = ApolloClient__React_Hooks_UseQuery.Extend({
      query: query,
      Raw: Raw,
      parse: parse,
      serialize: serialize,
      serializeVariables: serializeVariables
    });

var useLazy = include.useLazy;

var CompaniesQuery_refetchQueryDescription = include.refetchQueryDescription;

var CompaniesQuery_use = include.use;

var CompaniesQuery_useLazyWithVariables = include.useLazyWithVariables;

var CompaniesQuery = {
  CompaniesQuery_inner: CompaniesQuery_inner,
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables,
  refetchQueryDescription: CompaniesQuery_refetchQueryDescription,
  use: CompaniesQuery_use,
  useLazy: useLazy,
  useLazyWithVariables: CompaniesQuery_useLazyWithVariables
};

function Query_Lazy(Props) {
  var match = Curry.app(useLazy, [
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined
      ]);
  var queryResult = match[1];
  var executeQuery = match[0];
  var tmp;
  if (queryResult.TAG) {
    tmp = React.createElement(React.Fragment, undefined, "Waiting to be executed... ", React.createElement("button", {
              value: "execute",
              onClick: (function (param) {
                  return Curry._3(executeQuery, undefined, undefined, undefined);
                })
            }, "Execute"));
  } else {
    var match$1 = queryResult._0;
    var match$2 = match$1.data;
    if (match$2 !== undefined) {
      var companies = match$2.companies;
      var companyCount = companies !== undefined && companies.length !== 0 ? Belt_Array.keepMap(companies, (function (e) {
                return Caml_option.some(e);
              })).length : 0;
      tmp = React.createElement(React.Fragment, undefined, React.createElement("dialog", undefined, match$1.loading ? React.createElement("p", undefined, "Refreshing...") : null, match$1.error !== undefined ? React.createElement("p", undefined, "Something went wrong, data may be incomplete") : null), React.createElement("p", undefined, "There are " + (String(companyCount) + " Companies")));
    } else {
      tmp = match$1.loading ? React.createElement("p", undefined, "Loading") : React.createElement("p", undefined, "Error loading data");
    }
  }
  return React.createElement("div", undefined, tmp);
}

var make = Query_Lazy;

exports.CompaniesQuery = CompaniesQuery;
exports.make = make;
/* query Not a pure module */
